* 作業目標：<br>
  嘗試練習log的函式並應用<br>

* 作業重點：<br>
  學員需要複習log的轉換方式<br>
  熟悉運用指數函數以及對數函數

* 投影片：<br>
  正常的人耳能夠聽到最微弱的聲音叫作「聽覺閾」為 20 個微巴斯卡 (縮寫為 μPa) ，以聲壓 20μPa 定義為 0 分貝，表示 V0 為 20μPa，其餘聲壓為 V1(微巴斯卡)，如將 V1 帶入 200μPa，V0 為 20μPa，可以得到 GdB = 20*log10(200/20) = 20GdB。

* 題目：<br>
  * 【基本題】
     1. 【簡答題】請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？
     2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
     3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。
  * 【進階題】
     * 題目：
```
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]
```

     1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]<br>
     2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
     3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [10]:
import numpy as np 
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.16.5


* 【基本題】

In [21]:
#1.【簡答題】請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？
a = np.zeros((4,6))
b = np.empty((3,5))

print('a:', a, '；型態: ', a.dtype)
print('b:', b, '；型態: ', b.dtype)

a: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] ；型態:  float64
b: [[6.23042070e-307 1.89146896e-307 1.37961302e-306 1.05699242e-307
  8.01097889e-307]
 [1.78020169e-306 7.56601165e-307 1.02359984e-306 1.33510679e-306
  2.22522597e-306]
 [8.01097889e-307 1.60220800e-306 7.56601165e-307 2.22522596e-306
  3.91786943e-317]] ；型態:  float64


* zero 是建立0的數值
* empty是建立很接近0的數值，可以隨意更改

In [16]:
#2.在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
a = np.random.rand(2, 3)
b = np.array(a, dtype=int)

print('a:', a)
print('b:', b)

a: [[0.71901795 0.50063139 0.99253038]
 [0.97398425 0.9583742  0.38505516]]
b: [[0 0 0]
 [0 0 0]]


In [18]:
#3.承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。
m = 30
n = 40

h = np.random.rand (4,6)
print ('h:', h)
i = m+h*(n-m)
print ('i:', i)

h: [[0.4391379  0.79634134 0.35339042 0.09361332 0.51685039 0.64710896]
 [0.57914855 0.63066508 0.36117116 0.61629972 0.13755617 0.35169669]
 [0.46117545 0.38812637 0.80957012 0.99447445 0.08278509 0.70689762]
 [0.80062965 0.67561636 0.16040649 0.2829395  0.03167335 0.5986419 ]]
i: [[34.39137897 37.96341344 33.53390416 30.9361332  35.16850391 36.4710896 ]
 [35.79148546 36.30665085 33.61171156 36.16299718 31.37556167 33.51696685]
 [34.61175451 33.88126366 38.09570116 39.94474454 30.8278509  37.06897619]
 [38.00629648 36.7561636  31.60406495 32.829395   30.31673352 35.98641902]]


* 【進階題】

In [22]:
name_list = ['小明', '小華', '小菁', '小美', '小張', 'John', 'Mark', 'Tom']
sex_list = ['boy', 'boy', 'girl', 'girl', 'boy', 'boy', 'boy', 'boy']
weight_list = [67.5, 75.3, 50.1, 45.5, 80.8, 90.4, 78.4, 70.7]
rank_list = [8, 1, 5, 4, 7, 6, 2, 3]
myopia_list = [True, True, False, False, True, True, False, False]

In [26]:
#1.將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'), 'formats':('U10', 'U6', np.float_, np.int_, np.bool_)})
a = np.zeros(8,dtype=dt)
a['name'] = name_list
a['sex'] = sex_list
a['weight'] = weight_list
a['rank'] = rank_list
a['myopia'] = myopia_list

print(a)

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]


In [25]:
#2.呈上題，將array中體重(weight)數據集取出算出全部平均體重
np.average(a['weight'])

69.8375

In [27]:
#3.呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

boy_index = np.where(a['sex']=='boy')[0]
boy_mean = np.mean(a['weight'][boy_index])


girl_index = np.where(a['sex']=='girl')[0]
girl_mean = np.mean(a['weight'][girl_index])

print(boy_mean)
print(girl_mean)

77.18333333333332
47.8


In [2]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 20000
V0 = 20
a = 20 * np.log10( V1/V0 )
print( '分貝為', a )

分貝為 60.0


In [5]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式
V1 = 10**(30/20)*20
V2 = 10**(50/20)*20
print( '30分貝為50分貝的', V1/V2, '倍')

30分貝為50分貝的 0.09999999999999999 倍
