* 作業目標：<br>
  嘗試練習log的函式並應用<br>

* 作業重點：<br>
  學員需要複習log的轉換方式<br>
  熟悉運用指數函數以及對數函數

* 題目：<br>
  * 【基本題04】
     1. 【簡答題】 請問下列程式碼，運算結果分別為何？
```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```
     2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
     3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？
  * 【進階題04】
     * 投影片：<br>
       正常的人耳能夠聽到最微弱的聲音叫作「聽覺閾」為 20 個微巴斯卡 (縮寫為 μPa) ，以聲壓 20μPa 定義為 0 分貝，表示 V0 為 20μPa，其餘聲壓為 V1(微巴斯卡)，如將 V1 帶入 200μPa，V0 為 20μPa，可以得到 GdB = 20*log10(200/20) = 20GdB。
     * 運用投影片中的分貝公式回答下列問題。
       1. 正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
       2. 30分貝的聲壓會是50分貝的幾倍?

In [1]:
import numpy as np 
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.16.5


* 【基本題04】

In [9]:
#1. 【簡答題】 請問下列程式碼，運算結果分別為何？
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

print( 'a+a: ', a+a )
print( 'a+b: ', a+b )
print( 'a+c: ', a+c )
print( 'a+d: ', a+d )
print( 'a+e: ', a+e )  # 不符合Boardcast原則

a+a:  [ 40  60  80 100]
a+b:  [21 32 43 54]
a+c:  [21 31 41 51]
a+d:  [21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [16]:
#2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
A = np.ones(3)*1
B = np.ones(3)*2
print( (A+B)*(-A/2) )

[-1.5 -1.5 -1.5]


In [18]:
#3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？
A = np.ones((1,6))
B = np.ones((6,1))
print( np.dot(A,B) )   #內積
print( A @ B )         #內積
print('='*20)
print( np.outer(A,B) ) #外積
print( A * B)          #外積


[[6.]]
[[6.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


* 【進階題04】

In [14]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 20000
V0 = 20
a = 20 * np.log10( V1/V0 )
print( '分貝為', a )

分貝為 60.0


In [15]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式
V1 = 10**(30/20)*20
V2 = 10**(50/20)*20
print( '30分貝為50分貝的', V1/V2, '倍')

30分貝為50分貝的 0.09999999999999999 倍
