* 作業目標：
  * 在array中，可以靈活應用索引幫助資料擷取

* 作業重點：
  * 陣列的索引、切片、以及屬性，皆需要注意使用方式
  * 陣列之中索引式由0開始請同學注意

* 題目：<br>
  * 【基礎題01】
     1. 【簡答題】請問下列兩種將 Array 轉換成 List 的方式有何不同？<br>
     2. 請試著在程式中印出以下三個 NdArray 的屬性？<br>
        （屬性：ndim、shape、size、dtype、itemsize、length、type）<br>
     3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。<br>
  * 【進階題01】
     1. 生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
     2. 呈上題，將以上數列取出偶數。<br>
     3. 呈1題，將數列取出3的倍數。<br>

In [1]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.16.5


* 【基礎題01】

In [6]:
#1.【簡答題】請問下列兩種將 Array 轉換成 List 的方式有何不同？
#print('list(a): ', list(a))
#print('tolist(): ', a.tolist())
a = np.random.randint(10, size=6) 

print('list(a): ', list(a))
print('a.tolist(): ', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print('list(b): ', list(b))
print('b.tolist(): ', b.tolist())

'''
list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；tolist() 才能達成多層的型態轉換。
'''

list(a):  [2, 6, 1, 3, 4, 5]
a.tolist():  [2, 6, 1, 3, 4, 5]
list(b):  [array([2, 5]), array([5, 7]), array([5, 3])]
b.tolist():  [[2, 5], [5, 7], [5, 3]]


'\nlist(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；tolist() 才能達成多層的型態轉換。\n'

In [8]:
#2.請試著在程式中印出以下三個 NdArray 的屬性？
a = np.random.randint(10, size=6) 

print(a)
print('='*20)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[8 7 8 3 0 8]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [9]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print('='*20)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[9 3 9 6]
 [7 5 3 2]
 [7 7 5 1]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [10]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print('='*20)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[4 4]
  [5 2]
  [6 4]]

 [[2 1]
  [4 9]
  [6 0]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [11]:
#3.如何利用 list(...) 實現 a.tolist() 的效果？
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[3, 6, 6, 5, 0, 8]
[3, 6, 6, 5, 0, 8]


In [12]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[9, 5, 2, 7], [5, 5, 2, 4], [4, 6, 2, 8]]
[array([9, 5, 2, 7]), array([5, 5, 2, 4]), array([4, 6, 2, 8])]


* 【進階題01】

In [2]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
Seq = np.arange(0, 21, 1)
print( '等差數列: ', Seq)

等差數列:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
#2.呈上題，將以上數列取出偶數。
even_array = Seq[::2]
#even_array = [ i for i in Seq if i%2==0 ]
even_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
#3.呈1題，將數列取出3的倍數。
three_array = Seq[3::3]
#three_array = [ i for i in Seq if i%3==0 ]
three_array

array([ 3,  6,  9, 12, 15, 18])