* 作業目標：
  * 活用矩陣運算，實做線性代數

* 作業重點：
  * 線性代數公式應用
  * 矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

* 題目:<br>
  * 【基礎題】
     1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
     2. 如何從一個陣列中，找出出現頻率最高的數值與位置？
     3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
  * 【進階題】
  ```
  array1 = np.array([[10, 8], [3, 5]]) <br>
  ```
     1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
     2. 運用上列array計算特徵值、特徵向量?
     3. 運用上列array計算SVD?

In [1]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.19.2


In [23]:
import random
import timeit

【基礎題】

In [41]:
#1.請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
random.seed(99)
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
Z

array([[[6, 2, 1, ..., 9, 0, 7],
        [2, 0, 2, ..., 1, 0, 2],
        [8, 8, 8, ..., 5, 4, 0],
        ...,
        [3, 6, 3, ..., 1, 8, 6],
        [3, 2, 1, ..., 7, 5, 4],
        [4, 7, 8, ..., 5, 6, 7]],

       [[1, 1, 5, ..., 7, 9, 6],
        [6, 5, 9, ..., 3, 0, 5],
        [7, 3, 5, ..., 6, 5, 0],
        ...,
        [4, 0, 2, ..., 7, 3, 6],
        [7, 5, 6, ..., 4, 4, 0],
        [8, 7, 7, ..., 4, 0, 3]],

       [[9, 1, 3, ..., 6, 5, 3],
        [4, 1, 7, ..., 8, 6, 4],
        [4, 8, 7, ..., 3, 3, 8],
        ...,
        [5, 1, 6, ..., 3, 7, 2],
        [6, 9, 3, ..., 9, 1, 0],
        [8, 8, 5, ..., 3, 2, 9]],

       ...,

       [[0, 5, 7, ..., 7, 0, 2],
        [4, 0, 9, ..., 6, 9, 5],
        [4, 7, 8, ..., 3, 7, 8],
        ...,
        [3, 7, 0, ..., 7, 8, 4],
        [7, 8, 9, ..., 9, 8, 5],
        [4, 3, 6, ..., 7, 7, 3]],

       [[3, 9, 0, ..., 5, 9, 7],
        [5, 2, 3, ..., 2, 3, 2],
        [8, 9, 7, ..., 9, 1, 0],
        ...,
        [5, 1, 5, ..., 

In [42]:
%timeit -n 10 a = 2

Z + 1

82.9 ns ± 86.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 7,  3,  2, ..., 10,  1,  8],
        [ 3,  1,  3, ...,  2,  1,  3],
        [ 9,  9,  9, ...,  6,  5,  1],
        ...,
        [ 4,  7,  4, ...,  2,  9,  7],
        [ 4,  3,  2, ...,  8,  6,  5],
        [ 5,  8,  9, ...,  6,  7,  8]],

       [[ 2,  2,  6, ...,  8, 10,  7],
        [ 7,  6, 10, ...,  4,  1,  6],
        [ 8,  4,  6, ...,  7,  6,  1],
        ...,
        [ 5,  1,  3, ...,  8,  4,  7],
        [ 8,  6,  7, ...,  5,  5,  1],
        [ 9,  8,  8, ...,  5,  1,  4]],

       [[10,  2,  4, ...,  7,  6,  4],
        [ 5,  2,  8, ...,  9,  7,  5],
        [ 5,  9,  8, ...,  4,  4,  9],
        ...,
        [ 6,  2,  7, ...,  4,  8,  3],
        [ 7, 10,  4, ..., 10,  2,  1],
        [ 9,  9,  6, ...,  4,  3, 10]],

       ...,

       [[ 1,  6,  8, ...,  8,  1,  3],
        [ 5,  1, 10, ...,  7, 10,  6],
        [ 5,  8,  9, ...,  4,  8,  9],
        ...,
        [ 4,  8,  1, ...,  8,  9,  5],
        [ 8,  9, 10, ..., 10,  9,  6],
        [ 5,  4,  7, ...,  8,  8

In [43]:
for row in Z:
    for num in row:
        num += 1

%timeit -n 10 a = 2
Z

37.1 ns ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 7,  3,  2, ..., 10,  1,  8],
        [ 3,  1,  3, ...,  2,  1,  3],
        [ 9,  9,  9, ...,  6,  5,  1],
        ...,
        [ 4,  7,  4, ...,  2,  9,  7],
        [ 4,  3,  2, ...,  8,  6,  5],
        [ 5,  8,  9, ...,  6,  7,  8]],

       [[ 2,  2,  6, ...,  8, 10,  7],
        [ 7,  6, 10, ...,  4,  1,  6],
        [ 8,  4,  6, ...,  7,  6,  1],
        ...,
        [ 5,  1,  3, ...,  8,  4,  7],
        [ 8,  6,  7, ...,  5,  5,  1],
        [ 9,  8,  8, ...,  5,  1,  4]],

       [[10,  2,  4, ...,  7,  6,  4],
        [ 5,  2,  8, ...,  9,  7,  5],
        [ 5,  9,  8, ...,  4,  4,  9],
        ...,
        [ 6,  2,  7, ...,  4,  8,  3],
        [ 7, 10,  4, ..., 10,  2,  1],
        [ 9,  9,  6, ...,  4,  3, 10]],

       ...,

       [[ 1,  6,  8, ...,  8,  1,  3],
        [ 5,  1, 10, ...,  7, 10,  6],
        [ 5,  8,  9, ...,  4,  8,  9],
        ...,
        [ 4,  8,  1, ...,  8,  9,  5],
        [ 8,  9, 10, ..., 10,  9,  6],
        [ 5,  4,  7, ...,  8,  8

In [44]:
%timeit -n 10 a = 2

# type(np.array(np.nditer(Z)))
for d in np.array(np.nditer(Z)):
    d += 1

47.1 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [45]:
global Z
def plus_one():
    z1 = Z + 1
    return z1

%timeit -n 10 a = 2
plus_one()

47.1 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 8,  4,  3, ..., 11,  2,  9],
        [ 4,  2,  4, ...,  3,  2,  4],
        [10, 10, 10, ...,  7,  6,  2],
        ...,
        [ 5,  8,  5, ...,  3, 10,  8],
        [ 5,  4,  3, ...,  9,  7,  6],
        [ 6,  9, 10, ...,  7,  8,  9]],

       [[ 3,  3,  7, ...,  9, 11,  8],
        [ 8,  7, 11, ...,  5,  2,  7],
        [ 9,  5,  7, ...,  8,  7,  2],
        ...,
        [ 6,  2,  4, ...,  9,  5,  8],
        [ 9,  7,  8, ...,  6,  6,  2],
        [10,  9,  9, ...,  6,  2,  5]],

       [[11,  3,  5, ...,  8,  7,  5],
        [ 6,  3,  9, ..., 10,  8,  6],
        [ 6, 10,  9, ...,  5,  5, 10],
        ...,
        [ 7,  3,  8, ...,  5,  9,  4],
        [ 8, 11,  5, ..., 11,  3,  2],
        [10, 10,  7, ...,  5,  4, 11]],

       ...,

       [[ 2,  7,  9, ...,  9,  2,  4],
        [ 6,  2, 11, ...,  8, 11,  7],
        [ 6,  9, 10, ...,  5,  9, 10],
        ...,
        [ 5,  9,  2, ...,  9, 10,  6],
        [ 9, 10, 11, ..., 11, 10,  7],
        [ 6,  5,  8, ...,  9,  9

In [47]:
# 2.如何從一個陣列中，找出出現頻率最高的數值與位置？
Z = np.random.randint(0,10,50)
print(Z)

[2 6 3 3 6 6 5 9 0 9 9 3 9 2 8 2 4 0 8 8 3 5 6 3 5 0 5 8 7 9 4 8 2 0 6 1 5
 6 3 0 9 1 1 1 1 8 8 3 0 5]


In [50]:
# rint = np.argmax(np.bincount(Z))
uni, con = np.unique(Z, return_counts=True)
print('頻率最高的數值:', np.max(uni))
print('頻率最高的數值的次數:', con[np.argmax(uni)])
# from standard answer: "to find ALL the indexes"
print('頻率最高的數值的位置:', np.where(Z == np.max(uni))[0])

頻率最高的數值: 9
頻率最高的數值的次數: 6
頻率最高的數值的位置: [ 7  9 10 12 29 40]


In [46]:
# 3.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))
print('='*20)

b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))
print('='*20)

c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[0, 8, 3, 8, 1, 1]
[0, 8, 3, 8, 1, 1]
[[6, 0, 3, 8], [0, 2, 9, 4], [0, 0, 8, 0]]
[array([6, 0, 3, 8]), array([0, 2, 9, 4]), array([0, 0, 8, 0])]
[[[3, 3], [7, 3], [2, 7]], [[9, 0], [3, 0], [8, 9]]]
[array([[3, 3],
       [7, 3],
       [2, 7]]), array([[9, 0],
       [3, 0],
       [8, 9]])]


In [52]:
tolist_01 = lambda arr: list(map(tolist_01, arr)) if isinstance(arr, np.ndarray) else arr 
#isinstance is faster than type()
tolist_01(c)

[[[3, 3], [7, 3], [2, 7]], [[9, 0], [3, 0], [8, 9]]]

In [54]:
def tolist_02(arr):
    if (isinstance(arr, np.ndarray)):
        return(list(map(tolist_02, arr)))        
    else:
        return(arr)

tolist_02(c)

[[[3, 3], [7, 3], [2, 7]], [[9, 0], [3, 0], [8, 9]]]

In [56]:
def tolist_03(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    
    temp_list = []
    
    for row in iterable:
        temp_list.append(tolist_03(row))
    return temp_list

tolist_03(c)

[[[3, 3], [7, 3], [2, 7]], [[9, 0], [3, 0], [8, 9]]]

【進階題】

In [2]:
#1.運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

inv_array1 = np.linalg.inv( array1 )
print( '反矩陣 = \n', inv_array1 )

反矩陣 = 
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]


In [3]:
print( inv_array1 @ array1 )
print( array1 @ inv_array1 )

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [4]:
#2.運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)

print( '特徵值=', w, '\n' )
print( '特徵向量= \n', v )

特徵值= [13.  2.] 

特徵向量= 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [5]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))