* 作業目標<br>
  * 計算有缺失值的資料，統計量實作<br>

* 作業重點<br>
  * 當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
  * 計算統計量時不能出現缺失值

* 題目：<br>
  * 【基本題05】
     1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
     2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？   
  * 【進階題05_v1】
```
  english_score = np.array([55,89,76,65,48,70])<br>
  math_score = np.array([60,85,60,68,55,60])<br>
  chinese_score = np.array([65,90,82,72,66,77])<br>
```
     上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，運用上列數據回答下列問題。<br>
     1. 有多少學生英文成績比數學成績高?
     2. 是否全班同學最高分都是國文?
  * 【進階題05_v2】
```
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])
```

     上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>

     1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
     2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
     3. 用補考後資料找出與國文成績相關係數最高的學科?

In [2]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.19.2


【基本題05】

In [3]:
#1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
a = np.arange(11)+1
print(a)

a[(3 <= a) & (a < 7)] *= -1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [5]:
#2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
b = np.random.rand(3, 6)
print(b)

print(b[b > 0.5].size)

[[0.2333607  0.15583061 0.8633127  0.66629102 0.69835116 0.94573644]
 [0.03956573 0.16276819 0.9094251  0.89282478 0.73940203 0.66462101]
 [0.34872858 0.93984373 0.4614102  0.40843081 0.07095749 0.82438326]]
10


【進階題05_v1】

In [3]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [4]:
#1.有多少學生英文成績比數學成績高?
np.greater(english_score, math_score)

array([False,  True,  True, False, False,  True])

In [5]:
#2.是否全班同學最高分都是國文?
CH_EN = np.greater(chinese_score,english_score)
CH_MA = np.greater(chinese_score,math_score)
np.all(np.logical_and(CH_EN, CH_MA))

True

【進階題05_v2】

In [6]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [6]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

subject_list = ['英文', '數學', '國文']
score_list = [english_score, math_score, chinese_score]
for subject, score in zip(subject_list, score_list):
    if not np.any(np.isnan(score)):
        print( subject, '的成績:沒有缺漏值' )
        print( '平均 = ', np.mean(score) )
        print( '最大值 = ', np.max(score) )
        print( '最小值 = ', np.min(score) )
        print( '標準差 = ', np.std(score), '\n' )
    else: 
        print( subject, '的成績:含有缺漏值' )
        print( '平均 = ', np.nanmean(score) )
        print( '最大值 = ', np.nanmax(score) )
        print( '最小值 = ', np.nanmin(score) )
        print( '標準差 = ', np.nanstd(score) )
        print( '缺漏值:', np.isnan(score), '\n' )

英文 的成績:沒有缺漏值
平均 =  67.16666666666667
最大值 =  89
最小值 =  48
標準差 =  13.433995020924426 

數學 的成績:含有缺漏值
平均 =  66.6
最大值 =  85.0
最小值 =  60.0
標準差 =  9.707728879609279
缺漏值: [False False False False  True False] 

國文 的成績:沒有缺漏值
平均 =  75.33333333333333
最大值 =  90
最小值 =  65
標準差 =  8.825468196582484 



In [6]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

math_score[4] = 55
print( math_score )
print( '數學補考後:' )
print( '平均 = ', np.nanmean(math_score) )
print( '最大值 = ', np.nanmax(math_score) )
print( '最小值 = ', np.nanmin(math_score) )
print( '標準差 = ', np.nanstd(math_score) )

[60. 85. 60. 68. 55. 60.]
數學補考後:
平均 =  64.66666666666667
最大值 =  85.0
最小值 =  55.0
標準差 =  9.860132971832694


In [7]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

print( '國文與數學的相關係數: \n', np.corrcoef(chinese_score, math_score), '\n' )
print( '國文與英文的相關係數: \n', np.corrcoef(chinese_score, english_score) )

國文與數學的相關係數: 
 [[1.         0.74056803]
 [0.74056803 1.        ]] 

國文與英文的相關係數: 
 [[1.         0.97792828]
 [0.97792828 1.        ]]
