* 作業目標：
  * 熟悉陣列維度轉換，並且會擷取需要資料

* 作業重點：
  * 使用reshap須注意order用法
  * where可以運用邏輯條件擷取資料

* 題目：
  * 【基本題02】
     1. 【簡答題】 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
    
     ```
        print('type(a): ', type(a))
        print('a.dtype: ', a.dtype)
     ```
     
     2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式
     3. 【簡答題】 承上題，請判斷下列三種寫法為何不正確？
  * 【進階題02】
     1. 將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
     2. 呈上題的array，找出被6除餘1的數的索引
     
     ```
        def is_dtype(a, t):
            return a.dtype is t

        def is_dtype(a, t):
            return type(a) == np.dtype(t)

        def is_dtype(a, t):
            return type(a) is np.dtype(t)
     ```

In [2]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.16.5


* 【基本題02】

In [21]:
#1. 【簡答題】 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
a = np.linspace(2, 10, num=5, endpoint=True, dtype='int64')
print(a)
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)

[ 2  4  6  8 10]
type(a):  <class 'numpy.ndarray'>
a.dtype:  int64
type() 是檢查變數的型態，而不是元素的型態


* type()：回傳變數(a)的型態
* dtype()：回傳陣列(a)中的元素型態

In [17]:
#2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式
def is_dtype(a, t):
    return a.dtype is np.dtype(t)
#a = np.random.randint(10, size=6)
print(a)
print(is_dtype(a, 'int64'))

[ 2  4  6  8 10]
True


In [20]:
#3. 【簡答題】 承上題，請判斷下列三種寫法為何不正確？
def is_dtype01(a, t):   #1
    return a.dtype is t

def is_dtype02(a, t):
    return a.dtype is np.dtype(t)

def is_dtype03(a, t):
    return a.dtype == np.dtype(t)

def is_dtype04(a, t):
    return type(a) is t

def is_dtype05(a, t):   #2
    return type(a) == np.dtype(t)

def is_dtype06(a, t):   #3
    return type(a) is np.dtype(t)

is 相對 == 更嚴格，一定要型態正確才會回傳 True


In [19]:
print(is_dtype01(a, 'int64')) 
print(is_dtype02(a, 'int64'))
print(is_dtype03(a, 'int64')) 
print(is_dtype04(a, 'int64')) 
print(is_dtype05(a, 'int64'))
print(is_dtype06(a, 'int64')) 

False
True
True
False
False
False


In [22]:
print('type() 是檢查變數的型態，而不是元素的型態')
print('is 相對 == 更嚴格，一定要型態正確才會回傳 True')

type() 是檢查變數的型態，而不是元素的型態
is 相對 == 更嚴格，一定要型態正確才會回傳 True


* is 相對 == 更為嚴格，一定要全部正確才會回傳True

* 【進階題02】

In [9]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
array1.reshape((5, 6), order='F')

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [8]:
#2.呈上題的array，找出被6除餘1的數的索引
np.where( array1%6==1 )

(array([ 1,  7, 13, 19, 25], dtype=int64),)