<img width=150 src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/200px-NumPy_logo.svg.png"></img>

# Day-03 NumPy 陣列的初始化

* 除了數值資料之外，NumPy陣列也可以儲存複合式資料，也就是包含不同資料型別的元素。這就是結構化陣列 (Structured Arrays) 的功能，可以在陣列資料中指定名稱、型別，以進行後續的資料存取及處理。

## 匯入套件

In [ ]:
import numpy as np
print(np.__version__) # 1.16.5

1.22.4


## 建立/初始化陣列有四種方法

### 從內建型態作轉換

* Python 中有列表、元祖、字典和集合，可直接利用 `np.array()` 方法做型態轉換

```
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```

* 其中：
  * object：必填，任何 array_like 物件
  * dtype：指定轉成陣列後的元素型態
  * copy：預設為 True，是否產生一個新的物件
  * order：指定元素在記憶體中的儲存方式
* 補充：更多細節用法，請參考[官方文件](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

In [ ]:
print(np.array([1, 2, 3]))

# 會自動轉換成範圍比較大的型態：
print(np.array([1, 2, 3.0]), np.array([1, 2, 3.0]).dtype)

# 也可以指定成想要的型態：
print(np.array([1, 2, 3], dtype=complex), np.array([1, 2, 3], dtype=complex).dtype)

[1 2 3]
[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128


字典型態雖然可以成功被轉成陣列，不過好像不符合我們的預期

In [ ]:
print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)

{0: 123, 1: 456}
1


正確的寫法應該寫轉成有序的 List 再作轉換：

In [ ]:
print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size)

[[  0 123]
 [  1 456]]
4


### 從固定大小的初始值開始

* 先建立一個固定大小的初始值，例如由 0、1 或特定值所組成的陣列
* 建立元素全為 0 之一

In [ ]:
np.zeros((2, 3))
# 建立由 0 組成的 2x3 陣列

array([[0., 0., 0.],
       [0., 0., 0.]])

* 建立元素全為 0 之二
  * 使用 `empty()` 函式時不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定

In [ ]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

* 建立元素全為 1

In [ ]:
np.ones((2, 3))
# 建立由 1 組成的 2x3 陣列

array([[1., 1., 1.],
       [1., 1., 1.]])

* 建立元素全為 n

In [ ]:
np.full((2, 3), 9)
# 建立由 9 組成的 2x3 陣列

array([[9, 9, 9],
       [9, 9, 9]])

### 從固定大小的序列值開始

* 可以產生一個特定的序列值，有三種不同的序列：
  * 固定長度的等差序列
  * 固定區間的等差序列
  * 等比序列

In [ ]:
np.arange( 10, 30, 5 )
# array([10, 15, 20, 25])

array([10, 15, 20, 25])

In [ ]:
np.linspace( 0, 2, 3 )
# array([0. 1. 2.])

array([0., 1., 2.])

In [ ]:
np.logspace( 0, 2, 3 )
# array([1. 10. 100.])

array([  1.,  10., 100.])

### 從固定大小的亂數值開始

* 發現 np.random 其實還有許多種不同的亂數方法，發現這些隨機亂數最大的差別在於「分佈」

#### 【新版】
* numpy 1.16版以下無法使用

In [ ]:
from numpy.random import default_rng

In [ ]:
rng = default_rng()

normal = rng.standard_normal((3, 2))
random = rng.random((3, 2))
integers = rng.integers(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[-1.87389949  0.27757301]
 [ 0.05949928 -1.15602217]
 [ 0.26688927  1.38339595]]
[[0.12711796 0.93046184]
 [0.93236075 0.37161127]
 [0.02302414 0.17672433]]
[[4 2]
 [4 1]
 [0 1]]


#### 【舊版】

In [ ]:
normal = np.random.randn(2, 3)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[ 0.11061457  0.41556585 -0.52819422]
 [ 1.24677815 -0.29290536  0.43128301]]
[[0.1869718  0.178604  ]
 [0.33396573 0.00675724]
 [0.45728336 0.40361004]]
[[4 3]
 [4 7]
 [9 2]]


* 為什麼習慣建立一個「固定大小」的陣列？
  * 因為陣列的儲存特性，陣列的元素會配置在連續的記憶體位置。每次改動到大小對於記憶體的更動負擔是比較大的，因此希望在一開始就練利一組固定的尺寸避免頻繁改動記憶體

## 參考資料

* [Python 中的 list 與 NumPy 中 array 的區别 及相互轉換](https://blog.csdn.net/CatStarXcode/article/details/79039891)