<img width=150 src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/200px-NumPy_logo.svg.png"></img>

# Part.2-1-03 NumPy 結構化陣列 (Structured Arrays)

* 除了數值資料之外，NumPy陣列也可以儲存複合式資料，也就是包含不同資料型別的元素。這就是結構化陣列 (Structured Arrays) 的功能，可以在陣列資料中指定名稱、型別，以進行後續的資料存取及處理。

* 範例目標：
  實做結構化陣列 (Structured Arrays)
* 範例重點：
  結構化陣列可透過 dictionary 型別的資料建立 np.dtype 物件，並指定 dtype 給陣列
RecordArray 提供更多的屬性可以用來存取結構化陣列，但是相對的效能上較差於 Structured Array

# 【基礎03】

In [26]:
import numpy as np
print(np.__version__) 

1.16.5


## 0.建立/初始化陣列有四種方法：
  1. 從內建型態作轉換
  2. 從固定大小的初始值開始
  3. 從固定大小的序列值開始
  4. 從固定大小的亂數值開始

### 從內建型態作轉換：更多細節用法，請參考[官方文件](https://numpy.org/doc/stable/reference/generated/numpy.array.html)
  * object：必填，任何 array_like 物件
  * dtype：指定轉成陣列後的元素型態
  * copy：預設為 True，是否產生一個新的物件
  * order：指定元素在記憶體中的儲存方式

```
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```

In [2]:
print(np.array([1, 2, 3]))

# 會自動轉換成範圍比較大的型態：
print(np.array([1, 2, 3.0]), np.array([1, 2, 3.0]).dtype)

# 也可以指定成想要的型態：
print(np.array([1, 2, 3], dtype=complex), np.array([1, 2, 3], dtype=complex).dtype)

[1 2 3]
[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128


In [3]:
# 字典型態被轉成陣列不符合期待
print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)


# 正確的寫法應該寫轉成有序的 List 再作轉換
print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size)

{0: 123, 1: 456}
1
[[  0 123]
 [  1 456]]
4


字典型態雖然可以成功被轉成陣列，不過好像不符合我們的預期

In [5]:
np.array({0: 123, 1: 456})

array({0: 123, 1: 456}, dtype=object)

正確的寫法應該寫轉成有序的 List 再作轉換：

In [6]:
np.array(list({0: 123, 1: 456}.items()))

array([[  0, 123],
       [  1, 456]])

### 從固定大小的初始值開始
* 先建立一個固定大小的初始值，例如由 0、1 或特定值所組成的陣列

* 建立元素全為 0

In [12]:
np.zeros((2, 3))
# 建立由 0 組成的 2x3 陣列

array([[0., 0., 0.],
       [0., 0., 0.]])

另外一個類似的方法是

In [13]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

* 使用 empty() 函式則是不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定

* 建立元素全為 1

In [14]:
np.ones((2, 3))
# 建立由 1 組成的 2x3 陣列

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.full((2, 3), 9)
# 建立由 9 組成的 2x3 陣列

array([[9, 9, 9],
       [9, 9, 9]])

### 從固定大小的序列值開始
* 可以產生一個特定的序列值，有三種不同的序列：
  * 固定長度的等差序列
  * 固定區間的等差序列
  * 等比序列

In [16]:
np.arange( 10, 30, 5 )
# array([10, 15, 20, 25])

array([10, 15, 20, 25])

In [17]:
np.linspace( 0, 2, 3 )
# array([0. 1. 2.])

array([0., 1., 2.])

In [18]:
np.logspace( 0, 2, 3 )
# array([1. 10. 100.])

array([  1.,  10., 100.])

### 從固定大小的亂數值開始

### 【新版】
* (NOT RUN) numpy 1.16版無法使用

In [27]:
from numpy.random import default_rng

In [ ]:
rng = default_rng()

normal = rng.standard_normal((3, 2))
random = rng.random((3, 2))
integers = rng.integers(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

### 【舊版】

In [4]:
normal = np.random.randn(2, 3)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[ 0.11061457  0.41556585 -0.52819422]
 [ 1.24677815 -0.29290536  0.43128301]]
[[0.1869718  0.178604  ]
 [0.33396573 0.00675724]
 [0.45728336 0.40361004]]
[[4 3]
 [4 7]
 [9 2]]


# 【進階03】

## 1.資料型別 (dtype)

|資料型別|字母|Python資料型別|NumPy通用資料型別|
|---|---|---|---|
|boolean | '?'|bool|np.bool_|
|signed byte | 'b'|bytes|np.bytes_|
|unsigned byte | 'B'|bytes|np.bytes_|
|signed integer | 'i'|int|np.int_|
|unsigned integer | 'u'||np.uint|
|floating-point | 'f'|float|np.float_|
|complex-floating point | 'c'|complex|np.cfloat|
|timedelta | 'm'|datetime.timedelta|np.timedelta64|
|datetime | 'M'|datetime.datetime|np.datetime64|
|string|'S', 'a'|str|np.str_|
|Unicode string | 'U'|str|np.str_|

例如：在CSV檔中有不同型別的資料要讀取，我們可以指定各個Column的資料型別。

In [ ]:
%load structured.txt

透過 `numpy.dtype` 物件，指定要讀入各 Column 的資料型別，下面的例子分別示範 Python 的資料型別及字母代表的型別，其中字母後的數字代表其長度，例如： f8 代表 float64 (8 bytes)， U5 代表長度 5 以下的 unicode 字串。

* 資料型別也可以使用 NumPy 的資料型別，例如 `np.int32`。

In [9]:
# 使用字母代表的資料型別
dt = np.dtype('U5, i8, i8, U3')

In [8]:
a = np.genfromtxt("structured.txt", delimiter=',', dtype=dt)
a

array([('Jay', 1, 2, 'Yes'), ('James', 3, 4, 'No'), ('Joe', 5, 6, 'Yes')],
      dtype=[('f0', '<U5'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<U3')])

## 2. 結構化陣列 (Structured Arrays)

建立結構化陣列可透過 dictionary 型別的資料建立 `np.dtype` 物件，並指定 `dtype` 給陣列。

這邊的資料型別可以使用 Python 的資料型別、 NumPy 的資料型別、或是字母代表的型別皆可。在範例中我們混用了 3 種型別的表示方式。

In [10]:
dt = np.dtype({'names':('Name', 'num1', 'num2', 'True'), 'formats':((np.str_, 5), np.int32, int, 'U3')})

In [11]:
b = np.genfromtxt("structured.txt", delimiter=',', dtype=dt)
b

array([('Jay', 1, 2, 'Yes'), ('James', 3, 4, 'No'), ('Joe', 5, 6, 'Yes')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')])

建立陣列後，可以用索引的方式存取元素資料。

In [12]:
b[0]

('Jay', 1, 2, 'Yes')

也可以用Column名稱，取得Column所有元素值。

In [13]:
b['Name']

array(['Jay', 'James', 'Joe'], dtype='<U5')

或是單筆資料的欄位值。

In [16]:
b[1]['True']

'No'

也可以進行邏輯操作，取得對應的結果。

In [15]:
b[b['num2'] >= 3]['Name']

array(['James', 'Joe'], dtype='<U5')

## 3. 建立結構化陣列

上面的範例是從檔案中讀取的資料建立結構化陣列，如果要新建立一個結構化陣列，方式跟建立陣列非常類似。

下例使用 `zeros()` 初始化陣列，並指定 `dtype`。

In [18]:
c = np.zeros(3, dtype=dt)
c

array([('', 0, 0, ''), ('', 0, 0, ''), ('', 0, 0, '')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')])

In [19]:
print(c.dtype)

[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')]


In [20]:
name = ['Chloe', 'Charlotte', 'Clara']
num_1 = [11, 12, 13]
num_2 = [14, 15, 16]
check = ['Y', 'Y', 'N']

In [21]:
c['Name'] = name
c['num1'] = num_1
c['num2'] = num_2
c['True'] = check

In [22]:
print(c)

[('Chloe', 11, 14, 'Y') ('Charl', 12, 15, 'Y') ('Clara', 13, 16, 'N')]


## 4. RecordArray：`numpy.recarray()`

In [23]:
c_rec = c.view(np.recarray)
c_rec

rec.array([('Chloe', 11, 14, 'Y'), ('Charl', 12, 15, 'Y'),
           ('Clara', 13, 16, 'N')],
          dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')])

原先我們是透過索引或是名稱存取元素值，但是 RecordArray 可以使用屬性的方式來取得。

In [24]:
c_rec.Name

array(['Chloe', 'Charl', 'Clara'], dtype='<U5')